# Generated by Django 2.2.6 on 2019-10-19 18:34

from django.db import migrations, models
import overlays.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0002_overlay_plume'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='satallite_map',
            field=models.ImageField(null=True, upload_to=overlays.models.satallite_map_path),
        ),
    ]
